export const localizedValues: Record<string, Record<string, string>> = {
  EN: {
    welcome_title: 'Achieve Your Dream IELTS Score',
    welcome_desc: 'Join thousands of students who improved their band score with personalized practice',
    get_started: 'Get Started',
    target_score_title: "What's your target band score?",
    target_score_desc: 'This helps us create the right difficulty level.',
    continue_btn: 'Continue',
    test_type_title: 'Which IELTS test are you taking?',
    test_type_desc: "We'll tailor the practice materials to your test type.",
    academic: 'Academic',
    academic_desc: 'For higher education or professional registration',
    general: 'General Training',
    general_desc: 'For migration, work, or secondary education',
    test_date_title: 'When is your IELTS test?',
    test_date_desc: "We'll pace your study plan accordingly.",
    booked_switch: "I've booked my test",
    no_worries: 'No worries!',
    flexible_plan: "We'll create a flexible study plan you can adjust anytime.",
    level_title: "What's your current English level?",
    level_desc: 'Be honest — it helps us personalize your plan.',
    level_beg: 'Beginner',
    level_beg_desc: 'New to IELTS, band 4-5',
    level_int: 'Intermediate',
    level_int_desc: 'Some experience, band 5-6.5',
    level_adv: 'Advanced',
    level_adv_desc: 'Strong base, aiming for 7+',
    stoppers_title: "What's stopping you from reaching your goal?",
    stoppers_desc: 'Select all that apply.',
    stop_speaking: 'Speaking confidence',
    stop_reading: 'Reading speed',
    stop_writing: 'Writing structure',
    stop_listening: 'Listening comprehension',
    stop_time: 'Time management',
    stop_vocab: 'Vocabulary',
    study_time_title: 'How much time can you study daily?',
    study_time_desc: 'Even 15 minutes a day makes a difference.',
    time_15: '15 minutes',
    time_15_desc: 'Quick daily sessions',
    time_30: '30 minutes',
    time_30_desc: 'Steady progress',
    time_1h: '1 hour',
    time_1h_desc: 'Recommended pace',
    time_2h: '2+ hours',
    time_2h_desc: 'Intensive preparation',
    projected_title: 'Your projected IELTS score',
    projected_desc: 'Based on students with a similar profile.',
    projected_by_skill: 'Projected by skill',
    reminders_title: 'Stay on track with daily reminders',
    enjoying_title: 'Enjoying the app?',
    enjoying_desc: 'Your 5-star rating helps us keep the free updates coming!',
    rate_now: 'Rate Now',
    not_now: 'Not now',
    notifications_dialog: '"IELTS" Would Like to Send You Notifications',
    allow: 'Allow',
    dont_allow: "Don't Allow",
    personal_title: 'Make it personal',
    personal_desc: 'Allow tracking to unlock a smarter, more personal IELTS experience.',
    personal_opt1: 'Personalized for you',
    personal_opt1_desc: 'Study recommendations tuned to your goals and level',
    personal_opt2: 'Smarter over time',
    personal_opt2_desc: 'The more you practice, the better it adapts',
    personal_opt3: 'Help us grow',
    personal_opt3_desc: 'Lets us measure our ads so we can keep improving',
    paywall_title: 'Unlock your target IELTS Band Score',
    paywall_sub1: '12 Months (71% Off)',
    paywall_sub2: '1 Month',
    included_title: "WHAT'S INCLUDED",
    inc_speaking: 'AI Speaking Practice',
    inc_speaking_desc: 'Unlimited sessions with an AI examiner anytime. Get instant band scores on fluency, vocabulary, grammar, and pronunciation.',
    inc_mock: '300+ Full Mock Tests',
    inc_mock_desc: 'Practice with real IELTS-style tests for all four skills — Reading, Listening, Writing, and Speaking.',
    inc_writing: 'AI Writing Correction',
    inc_writing_desc: 'Submit Task 1 or Task 2 essays and receive detailed band score feedback with grammar and coherence tips.',
    inc_plan: 'Personalized Study Plan',
    inc_plan_desc: 'Your daily plan adapts to your current band score, weak skills, and exam date to keep you on track.',
    inc_track: 'Band Score Progress Tracker',
    inc_track_desc: 'Visualize your improvement over time with detailed stats.',
    dashboard_greeting_morning: 'Good Morning ☀️',
    dashboard_greeting_night: 'Good Night 🌙',
    level_pre_int: 'Pre-Intermediate',
    level_sub: 'Start practicing to track your level!',
    practice_area: 'Practice Area',
    continue_learning: 'Continue Learning',
    menu_home: 'Home',
    menu_plan: 'Plan',
    menu_tools: 'Tools',
    menu_history: 'History',
    menu_settings: 'Settings',
    essay_checker: 'Essay Checker',
    essay_checker_desc: 'Get AI band score & feedback',
    grammar_check: 'Grammar Check',
    grammar_check_desc: 'Find & fix grammar errors',
    paraphrase: 'Paraphrase',
    paraphrase_desc: 'Rewrite sentences 3 ways',
    vocabulary: 'Vocabulary',
    vocabulary_desc: 'Build IELTS vocabulary',
    speaking_samples: 'Speaking Samples',
    speaking_samples_desc: 'Band 9 answers for Part 1-3',
    writing_samples: 'Writing Samples',
    writing_samples_desc: 'Band 9 essays & reports',
    band_calculator: 'Overall Band Calculator',
    band_calculator_desc: 'Calculate your overall IELTS band from 4 skill scores',
    schedule_title: 'Your Schedule',
    ai_tools_title: 'AI Tools',
    ai_tools_desc: 'Powerful tools to boost your IELTS preparation',
    free_plan: 'Free Plan',
    upgrade_plan: 'Upgrade for full access',
    upgrade: 'Upgrade',
    exam_type: 'Exam Type',
    target_band: 'Target Band',
    reset_plan: 'Reset Study Plan',
    send_feedback: 'Send Feedback',
    rate_app: 'Rate App',
    privacy_policy: 'Privacy Policy',
    terms_of_use: 'Terms of Use',
    daily_reminders: 'Daily reminders & updates',
  },
  AR: {
    welcome_title: 'حقق درجتك التي تحلم بها في الآيلتس',
    welcome_desc: 'انضم إلى آلاف الطلاب الذين حسنوا درجاتهم من خلال الممارسة المخصصة',
    get_started: 'ابدأ الآن',
    target_score_title: 'ما هي الدرجة المستهدفة؟',
    target_score_desc: 'يساعدنا هذا في إنشاء مستوى الصعوبة المناسب.',
    continue_btn: 'متابعة',
    test_type_title: 'أي اختبار آيلتس ستأخذه؟',
    test_type_desc: 'سنقوم بتفصيل مواد الممارسة حسب نوع الاختبار الخاص بك.',
    academic: 'الأكاديمي',
    academic_desc: 'للتعليم العالي أو التسجيل المهني',
    general: 'التدريب العام',
    general_desc: 'للهجرة أو العمل أو التعليم الثانوي',
    test_date_title: 'متى اختبار الآيلتس الخاص بك؟',
    test_date_desc: 'سنقوم بضبط وتيرة خطتك الدراسية بناءً على ذلك.',
    booked_switch: 'لقد قمت بحجز اختباري',
    no_worries: 'لا تقلق!',
    flexible_plan: 'سننشئ خطة دراسية مرنة يمكنك تعديلها في أي وقت.',
    level_title: 'ما هو مستواك الحالي في اللغة الإنجليزية؟',
    level_desc: 'كن صادقًا — فهذا يساعدنا في تخصيص خطتك.',
    level_beg: 'مبتدئ',
    level_beg_desc: 'جديد في الآيلتس، النطاق 4-5',
    level_int: 'متوسط',
    level_int_desc: 'لديه بعض الخبرة، النطاق 5-6.5',
    level_adv: 'متقدم',
    level_adv_desc: 'أساس قوي، يستهدف 7+',
    stoppers_title: 'ما الذي يمنعك من الوصول إلى هدفك؟',
    stoppers_desc: 'اختر كل ما ينطبق.',
    stop_speaking: 'الثقة في التحدث',
    stop_reading: 'سرعة القراءة',
    stop_writing: 'بنية الكتابة',
    stop_listening: 'فهم الاستماع',
    stop_time: 'إدارة الوقت',
    stop_vocab: 'المفردات',
    study_time_title: 'كم من الوقت يمكنك الدراسة يومياً؟',
    study_time_desc: 'حتى 15 دقيقة يومياً تصنع فارقاً.',
    time_15: '15 دقيقة',
    time_15_desc: 'جلسات يومية سريعة',
    time_30: '30 دقيقة',
    time_30_desc: 'تقدم ثابت',
    time_1h: 'ساعة واحدة',
    time_1h_desc: 'الوتيرة الموصى بها',
    time_2h: 'ساعتين أو أكثر',
    time_2h_desc: 'إعداد مكثف',
    projected_title: 'درجتك المتوقعة في الآيلتس',
    projected_desc: 'بناءً على الطلاب الذين لديهم ملف تعريف مماثل.',
    projected_by_skill: 'المتوقع حسب المهارة',
    reminders_title: 'ابقَ على المسار الصحيح مع تذكيرات يومية',
    enjoying_title: 'هل تستمتع بالتطبيق؟',
    enjoying_desc: 'تقييمك بـ 5 نجوم يساعدنا في مواصلة تقديم التحديثات المجانية!',
    rate_now: 'تقييم الآن',
    not_now: 'ليس الآن',
    notifications_dialog: 'يريد "IELTS" إرسال إشعارات إليك',
    allow: 'سماح',
    dont_allow: 'عدم السماح',
    personal_title: 'اجعله مخصصاً',
    personal_desc: 'السماح بالتتبع لفتح تجربة آيلتس أكثر ذكاءً وشخصية.',
    personal_opt1: 'مخصص لك',
    personal_opt1_desc: 'توصيات دراسية مخصصة لأهدافك ومستواك',
    personal_opt2: 'أكثر ذكاءً بمرور الوقت',
    personal_opt2_desc: 'كلما مارست أكثر، كلما تكيف التطبيق بشكل أفضل',
    personal_opt3: 'ساعدنا على النمو',
    personal_opt3_desc: 'يتيح لنا قياس إعلاناتنا لنستمر في التحسن',
    paywall_title: 'افتح درجتك المستهدفة في الآيلتس',
    paywall_sub1: '12 شهراً (خصم 71%)',
    paywall_sub2: 'شهر واحد',
    included_title: 'ما تشمله الباقة',
    inc_speaking: 'ممارسة التحدث بالذكاء الاصطناعي',
    inc_speaking_desc: 'جلسات غير محدودة مع مصحح ذكاء اصطناعي في أي وقت. احصل على درجات فورية.',
    inc_mock: '300+ اختبار تجريبي كامل',
    inc_mock_desc: 'تدرب على اختبارات حقيقية تشمل المهارات الأربع.',
    inc_writing: 'تصحيح الكتابة بالذكاء الاصطناعي',
    inc_writing_desc: 'أرسل المقالات واحصل على تقييم تفصيلي.',
    inc_plan: 'خطة دراسية مخصصة',
    inc_plan_desc: 'تتكيف خطتك اليومية مع درجاتك ونقاط ضعفك.',
    inc_track: 'متابع تقدم الدرجات',
    inc_track_desc: 'اعرض تقدمك بمرور الوقت بإحصاءات مفصلة.',
    dashboard_greeting_morning: 'صباح الخير ☀️',
    dashboard_greeting_night: 'مساء الخير 🌙',
    level_pre_int: 'دون المتوسط',
    level_sub: 'ابدأ التدريب لتتبع مستواك!',
    practice_area: 'منطقة التدريب',
    continue_learning: 'واصل التعلم',
    menu_home: 'الرئيسية',
    menu_plan: 'الخطة',
    menu_tools: 'الأدوات',
    menu_history: 'السجل',
    menu_settings: 'الإعدادات',
    essay_checker: 'مصحح المقالات',
    essay_checker_desc: 'احصل على درجات وملاحظات بالذكاء الاصطناعي',
    grammar_check: 'فحص القواعد',
    grammar_check_desc: 'ابحث عن الأخطاء النحوية وصححها',
    paraphrase: 'إعادة الصياغة',
    paraphrase_desc: 'أعد صياغة الجمل بثلاث طرق',
    vocabulary: 'المفردات',
    vocabulary_desc: 'ابنِ مفرداتك للآيلتس',
    speaking_samples: 'عينات التحدث',
    speaking_samples_desc: 'إجابات نموذجية للنطاق 9 للآجزاء 1-3',
    writing_samples: 'عينات الكتابة',
    writing_samples_desc: 'مقالات وتقارير نموذجية للنطاق 9',
    band_calculator: 'حاسبة النطاق الإجمالي',
    band_calculator_desc: 'احسب درجتك الإجمالية من درجات المهارات الأربع',
    schedule_title: 'جدولك الدراسي',
    ai_tools_title: 'أدوات الذكاء الاصطناعي',
    ai_tools_desc: 'أدوات قوية لتعزيز استعدادك للآيلتس',
    free_plan: 'الخطة المجانية',
    upgrade_plan: 'ترقية للوصول الكامل',
    upgrade: 'ترقية',
    exam_type: 'نوع الاختبار',
    target_band: 'الدرجة المستهدفة',
    reset_plan: 'إعادة تعيين خطة الدراسة',
    send_feedback: 'أرسل ملاحظاتك',
    rate_app: 'تقييم التطبيق',
    privacy_policy: 'سياسة الخصوصية',
    terms_of_use: 'شروط الاستخدام',
    daily_reminders: 'التذكيرات والتحديثات اليومية',
  },
  FR: {
    welcome_title: 'Obtenez votre score IELTS de rêve',
    welcome_desc: 'Rejoignez des milliers de personnes qui ont progressé grâce à la pratique personnalisée.',
    get_started: 'Commencer',
    continue_btn: 'Continuer',
    level_beg: 'Débutant',
    level_int: 'Intermédiaire',
    level_adv: 'Avancé',
    level_sub: 'Commencez à pratiquer pour suivre votre niveau !',
    practice_area: 'Zone de pratique',
    continue_learning: 'Continuer l\'apprentissage',
    menu_home: 'Accueil',
    menu_plan: 'Plan d\'étude',
    menu_tools: 'Outils',
    menu_history: 'Historique',
    menu_settings: 'Paramètres',
    essay_checker: 'Correcteur d\'essai',
    grammar_check: 'Correction de grammaire',
    paraphrase: 'Paraphraser',
    vocabulary: 'Vocabulaire',
    speaking_samples: 'Échantillons d\'expression',
    writing_samples: 'Exemples d\'écriture',
    band_calculator: 'Calculateur de score',
    free_plan: 'Plan gratuit',
    upgrade_plan: 'Mettre à niveau pour accès complet',
    upgrade: 'Mettre à niveau',
  },
  DE: {
    welcome_title: 'Erreichen Sie Ihre IELTS-Wunschband',
    welcome_desc: 'Schließen Sie sich Tausenden an, die sich durch personalisiertes Training verbessert haben.',
    get_started: 'Loslegen',
    continue_btn: 'Weiter',
    level_beg: 'Anfänger',
    level_int: 'Mittelstufe',
    level_adv: 'Fortgeschritten',
    level_sub: 'Beginnen Sie mit dem Training, um Ihr Niveau zu verfolgen!',
    practice_area: 'Übungsbereich',
    continue_learning: 'Lernen fortsetzen',
    menu_home: 'Startseite',
    menu_plan: 'Lernplan',
    menu_tools: 'Werkzeuge',
    menu_history: 'Verlauf',
    menu_settings: 'Einstellungen',
    essay_checker: 'Aufsatzprüfer',
    grammar_check: 'Grammatikprüfung',
    paraphrase: 'Paraphrasieren',
    vocabulary: 'Wortschatz',
    speaking_samples: 'Sprechproben',
    writing_samples: 'Schreibproben',
    band_calculator: 'Notenrechner',
    free_plan: 'Kostenloser Plan',
    upgrade_plan: 'Upgrade für vollen Zugriff',
    upgrade: 'Upgrade',
  },
  IT: {
    welcome_title: 'Raggiungi il tuo punteggio IELTS ideale',
    welcome_desc: 'Unisciti a migliaia di studenti che hanno migliorato la loro preparazione.',
    get_started: 'Inizia ora',
    continue_btn: 'Continua',
    level_beg: 'Principiante',
    level_int: 'Intermedio',
    level_adv: 'Avanzato',
    level_sub: 'Inizia a praticare per tracciare il tuo livello!',
    practice_area: 'Area di pratica',
    continue_learning: 'Continua ad apprendere',
    menu_home: 'Home',
    menu_plan: 'Piano di studi',
    menu_tools: 'Strumenti',
    menu_history: 'Cronologia',
    menu_settings: 'Impostazioni',
    essay_checker: 'Correttore di saggi',
    grammar_check: 'Controllo grammaticale',
    paraphrase: 'Parafrasi',
    vocabulary: 'Vocabolario',
    speaking_samples: 'Campioni parlati',
    writing_samples: 'Esempi di scrittura',
    band_calculator: 'Calcolatore punteggio',
    free_plan: 'Piano gratuito',
    upgrade_plan: 'Aggiorna per accesso completo',
    upgrade: 'Aggiorna',
  },
  JA: {
    welcome_title: '憧れのIELTSスコアを獲得',
    welcome_desc: 'パーソナライズされた練習で目標スコアを達成しましょう。',
    get_started: '始める',
    continue_btn: '次へ',
    level_beg: '初心者',
    level_int: '中級者',
    level_adv: '上級者',
    level_sub: '練習を始めてレベルを追跡しましょう！',
    practice_area: '練習エリア',
    continue_learning: '学習を続ける',
    menu_home: 'ホーム',
    menu_plan: '学習プラン',
    menu_tools: 'ツール',
    menu_history: '履歴',
    menu_settings: '設定',
    essay_checker: 'エッセイチェッカー',
    grammar_check: '文法チェック',
    paraphrase: '言い換え',
    vocabulary: '語彙',
    speaking_samples: 'スピーキングサンプル',
    writing_samples: 'ライティングサンプル',
    band_calculator: 'バンドスコア計算機',
    free_plan: '無料プラン',
    upgrade_plan: 'フルアクセスにアップグレード',
    upgrade: 'アップグレード',
  },
  KO: {
    welcome_title: '목표하는 IELTS 점수를 달성하세요',
    welcome_desc: '개인 맞춤형 연습을 통해 실력을 향상시킨 수천 명의 학생들과 함께하세요.',
    get_started: '시작하기',
    continue_btn: '계속하기',
    level_beg: '초급',
    level_int: '중급',
    level_adv: '고급',
    level_sub: '연습을 시작하여 실력을 추적해 보세요!',
    practice_area: '연습 영역',
    continue_learning: '계속 학습하기',
    menu_home: '홈',
    menu_plan: '학습 계획',
    menu_tools: '도구',
    menu_history: '기록',
    menu_settings: '설정',
    essay_checker: '에세이 검사기',
    grammar_check: '문법 검사',
    paraphrase: '패러프레이징',
    vocabulary: '어휘',
    speaking_samples: '스피킹 샘플',
    writing_samples: '라이팅 샘플',
    band_calculator: '밴드 스코어 계산기',
    free_plan: '무료 요금제',
    upgrade_plan: '전체 액세스 업그레이드',
    upgrade: '업그레이드',
  },
  PT: {
    welcome_title: 'Alcance a nota dos seus sonhos no IELTS',
    welcome_desc: 'Junte-se a milhares de estudantes que melhoraram seu desempenho.',
    get_started: 'Começar',
    continue_btn: 'Continuar',
    level_beg: 'Iniciante',
    level_int: 'Intermediário',
    level_adv: 'Avançado',
    level_sub: 'Comece a praticar para acompanhar seu progresso!',
    practice_area: 'Área de prática',
    continue_learning: 'Continuar aprendendo',
    menu_home: 'Início',
    menu_plan: 'Plano de estudo',
    menu_tools: 'Ferramentas',
    menu_history: 'Histórico',
    menu_settings: 'Configurações',
    essay_checker: 'Corretor de redação',
    grammar_check: 'Corretor gramatical',
    paraphrase: 'Parafrasear',
    vocabulary: 'Vocabulário',
    speaking_samples: 'Amostras de fala',
    writing_samples: 'Amostras de escrita',
    band_calculator: 'Calculadora de notas',
    free_plan: 'Plano gratuito',
    upgrade_plan: 'Atualizar para acesso total',
    upgrade: 'Atualizar',
  },
  RU: {
    welcome_title: 'Достигните желаемого балла IELTS',
    welcome_desc: 'Присоединяйтесь к тысячам студентов, улучшивших свои результаты.',
    get_started: 'Начать',
    continue_btn: 'Продолжить',
    level_beg: 'Новичок',
    level_int: 'Средний',
    level_adv: 'Продвинутый',
    level_sub: 'Начните практиковаться для отслеживания своего уровня!',
    practice_area: 'Практика',
    continue_learning: 'Продолжить обучение',
    menu_home: 'Главная',
    menu_plan: 'План обучения',
    menu_tools: 'Инструменты',
    menu_history: 'История',
    menu_settings: 'Настройки',
    essay_checker: 'Проверка эссе',
    grammar_check: 'Проверка грамматики',
    paraphrase: 'Парафраз',
    vocabulary: 'Словарь',
    speaking_samples: 'Примеры устной речи',
    writing_samples: 'Примеры сочинений',
    band_calculator: 'Калькулятор баллов',
    free_plan: 'Бесплатный план',
    upgrade_plan: 'Обновить для полного доступа',
    upgrade: 'Обновить',
  },
  ZH: {
    welcome_title: '取得您理想的 IELTS 分数',
    welcome_desc: '加入数千名通过个性化练习提升雅思成绩的学生行列。',
    get_started: '开始使用',
    continue_btn: '继续',
    level_beg: '初学者',
    level_int: '中级',
    level_adv: '高级',
    level_sub: '开始练习以追踪您的水平！',
    practice_area: '练习区域',
    continue_learning: '继续学习',
    menu_home: '首页',
    menu_plan: '学习计划',
    menu_tools: '工具',
    menu_history: '历史记录',
    menu_settings: '设置',
    essay_checker: '作文批改',
    grammar_check: '语法检查',
    paraphrase: '同义改写',
    vocabulary: '词汇积累',
    speaking_samples: '口语范文',
    writing_samples: '写作范文',
    band_calculator: '总分计算器',
    free_plan: '免费版',
    upgrade_plan: '升级以解锁全部功能',
    upgrade: '升级',
  },
  ES: {
    welcome_title: 'Consigue tu puntuación ideal en el IELTS',
    welcome_desc: 'Únete a miles de estudiantes que mejoraron sus resultados.',
    get_started: 'Comenzar',
    continue_btn: 'Continuar',
    level_beg: 'Principiante',
    level_int: 'Intermedio',
    level_adv: 'Avanzado',
    level_sub: '¡Comienza a practicar para ver tu nivel!',
    practice_area: 'Área de práctica',
    continue_learning: 'Continuar aprendiendo',
    menu_home: 'Inicio',
    menu_plan: 'Plan de estudio',
    menu_tools: 'Herramientas',
    menu_history: 'Historial',
    menu_settings: 'Ajustes',
    essay_checker: 'Corrector de ensayos',
    grammar_check: 'Corrector de gramática',
    paraphrase: 'Parafrasear',
    vocabulary: 'Vocabulario',
    speaking_samples: 'Ejemplos de habla',
    writing_samples: 'Ejemplos de escritura',
    band_calculator: 'Calculadora de puntajes',
    free_plan: 'Plan gratuito',
    upgrade_plan: 'Actualizar para acceso completo',
    upgrade: 'Actualizar',
  },
  TH: {
    welcome_title: 'คว้าคะแนน IELTS ในฝันของคุณ',
    welcome_desc: 'เข้าร่วมกับนักเรียนหลายพันคน ที่พัฒนาทักษะผ่านการฝึกฝนเฉพาะตัว.',
    get_started: 'เริ่มเลย',
    continue_btn: 'ดำเนินการต่อ',
    level_beg: 'ระดับเริ่มต้น',
    level_int: 'ระดับกลาง',
    level_adv: 'ระดับสูง',
    level_sub: 'เริ่มฝึกฝนเพื่อติดตามระดับทักษะของคุณ!',
    practice_area: 'พื้นที่ฝึกฝน',
    continue_learning: 'เรียนรู้ต่อ',
    menu_home: 'หน้าแรก',
    menu_plan: 'แผนการเรียน',
    menu_tools: 'เครื่องมือ',
    menu_history: 'ประวัติการใช้งาน',
    menu_settings: 'การตั้งค่า',
    essay_checker: 'ตรวจเรียงความ',
    grammar_check: 'ตรวจไวยากรณ์',
    paraphrase: 'ถอดความ',
    vocabulary: 'คำศัพท์',
    speaking_samples: 'ตัวอย่างการพูด',
    writing_samples: 'ตัวอย่างการเขียน',
    band_calculator: 'เครื่องคำนวณคะแนน',
    free_plan: 'แผนบริการฟรี',
    upgrade_plan: 'อัปเกรดเพื่อการเข้าถึงเต็มรูปแบบ',
    upgrade: 'อัปเกรด',
  },
  ZHT: {
    welcome_title: '取得您理想的 IELTS 分數',
    welcome_desc: '加入數千名通過個性化練習提升雅思成績的學生行列。',
    get_started: '開始使用',
    continue_btn: '繼續',
    level_beg: '初學者',
    level_int: '中級',
    level_adv: '高級',
    level_sub: '開始練習以追蹤您的水平！',
    practice_area: '練習區域',
    continue_learning: '繼續學習',
    menu_home: '首頁',
    menu_plan: '學習計劃',
    menu_tools: '工具',
    menu_history: '歷史記錄',
    menu_settings: '設置',
    essay_checker: '作文批改',
    grammar_check: '語法檢查',
    paraphrase: '同義改寫',
    vocabulary: '詞彙積累',
    speaking_samples: '口語範文',
    writing_samples: '寫作範文',
    band_calculator: '總分計算器',
    free_plan: '免費版',
    upgrade_plan: '升級以解鎖全部功能',
    upgrade: '升級',
  },
  UK: {
    welcome_title: 'Досягніть бажаного балу IELTS',
    welcome_desc: 'Приєднуйтесь до тисяч студентів, які покращили свої результати.',
    get_started: 'Почати',
    continue_btn: 'Продовжити',
    level_beg: 'Початківець',
    level_int: 'Середній',
    level_adv: 'Просунутий',
    level_sub: 'Почніть практикуватися для відстеження свого рівня!',
    practice_area: 'Зона практики',
    continue_learning: 'Продовжувати навчання',
    menu_home: 'Головна',
    menu_plan: 'План навчання',
    menu_tools: 'Інструменти',
    menu_history: 'Історія',
    menu_settings: 'Налаштування',
    essay_checker: 'Перевірка есе',
    grammar_check: 'Перевірка граматики',
    paraphrase: 'Парафраз',
    vocabulary: 'Словниковий запас',
    speaking_samples: 'Зразки усного мовлення',
    writing_samples: 'Зразки письмових робіт',
    band_calculator: 'Калькулятор балів',
    free_plan: 'Безкоштовний тариф',
    upgrade_plan: 'Оновити для повного доступу',
    upgrade: 'Оновити',
  },
  VI: {
    welcome_title: 'Đạt điểm số IELTS mơ ước của bạn',
    welcome_desc: 'Tham gia cùng hàng ngàn học viên đã cải thiện điểm số thông qua lộ trình học cá nhân.',
    get_started: 'Bắt đầu',
    continue_btn: 'Tiếp tục',
    level_beg: 'Người mới bắt đầu',
    level_int: 'Trung cấp',
    level_adv: 'Nâng cao',
    level_sub: 'Bắt đầu luyện tập để theo dõi trình độ!',
    practice_area: 'Khu vực luyện tập',
    continue_learning: 'Tiếp tục học',
    menu_home: 'Trang chủ',
    menu_plan: 'Lộ trình học',
    menu_tools: 'Công cụ',
    menu_history: 'Lịch sử',
    menu_settings: 'Cài đặt',
    essay_checker: 'Chấm điểm bài viết',
    grammar_check: 'Sửa lỗi ngữ pháp',
    paraphrase: 'Diễn đạt lại',
    vocabulary: 'Từ vựng',
    speaking_samples: 'Bài nói mẫu',
    writing_samples: 'Bài viết mẫu',
    band_calculator: 'Tính điểm tổng',
    free_plan: 'Gói miễn phí',
    upgrade_plan: 'Nâng cấp để mở khóa toàn bộ',
    upgrade: 'Nâng cấp',
  },
};

export const languagesList = [
  { code: 'EN', name: 'English' },
  { code: 'AR', name: 'العربية (Arabic)' },
  { code: 'FR', name: 'Français (French)' },
  { code: 'DE', name: 'Deutsch (German)' },
  { code: 'IT', name: 'Italiano (Italian)' },
  { code: 'JA', name: '日本語 (Japanese)' },
  { code: 'KO', name: '한국어 (Korean)' },
  { code: 'PT', name: 'Português (Portuguese)' },
  { code: 'RU', name: 'Русский (Russian)' },
  { code: 'ZH', name: '简体中文 (Simplified Chinese)' },
  { code: 'ES', name: 'Español (Spanish)' },
  { code: 'TH', name: 'ไทย (Thai)' },
  { code: 'ZHT', name: '繁體中文 (Traditional Chinese)' },
  { code: 'UK', name: 'Українська (Ukrainian)' },
  { code: 'VI', name: 'Tiếng Việt (Vietnamese)' },
];

export function getTranslation(key: string, locale: string = 'EN'): string {
  if (localizedValues[locale] && localizedValues[locale][key]) {
    return localizedValues[locale][key];
  }
  return localizedValues['EN'][key] || key;
}
