export const localizedValues: Record<string, Record<string, string>> = {
  EN: {
    welcome_title: 'Achieve Your Dream IELTS Score',
    welcome_desc: 'Join thousands of students who improved their band score with personalized practice',
    get_started: 'Get Started',
    target_score_title: "What's your target band score?",
    target_score_desc: 'This helps us create the right difficulty level.',
    continue_btn: 'Continue',
    test_type_title: 'Which IELTS test are you taking?',
    test_type_desc: "We'll tailor the practice materials to your test type.",
    academic: 'Academic',
    academic_desc: 'For higher education or professional registration',
    general: 'General Training',
    general_desc: 'For migration, work, or secondary education',
    test_date_title: 'When is your IELTS test?',
    test_date_desc: "We'll pace your study plan accordingly.",
    booked_switch: "I've booked my test",
    no_worries: 'No worries!',
    flexible_plan: "We'll create a flexible study plan you can adjust anytime.",
    level_title: "What's your current English level?",
    level_desc: 'Be honest — it helps us personalize your plan.',
    level_beg: 'Beginner',
    level_beg_desc: 'New to IELTS, band 4-5',
    level_int: 'Intermediate',
    level_int_desc: 'Some experience, band 5-6.5',
    level_adv: 'Advanced',
    level_adv_desc: 'Strong base, aiming for 7+',
    stoppers_title: "What's stopping you from reaching your goal?",
    stoppers_desc: 'Select all that apply.',
    stop_speaking: 'Speaking confidence',
    stop_reading: 'Reading speed',
    stop_writing: 'Writing structure',
    stop_listening: 'Listening comprehension',
    stop_time: 'Time management',
    stop_vocab: 'Vocabulary',
    study_time_title: 'How much time can you study daily?',
    study_time_desc: 'Even 15 minutes a day makes a difference.',
    time_15: '15 minutes',
    time_15_desc: 'Quick daily sessions',
    time_30: '30 minutes',
    time_30_desc: 'Steady progress',
    time_1h: '1 hour',
    time_1h_desc: 'Recommended pace',
    time_2h: '2+ hours',
    time_2h_desc: 'Intensive preparation',
    projected_title: 'Your projected IELTS score',
    projected_desc: 'Based on students with a similar profile.',
    projected_by_skill: 'Projected by skill',
    reminders_title: 'Stay on track with daily reminders',
    enjoying_title: 'Enjoying the app?',
    enjoying_desc: 'Your 5-star rating helps us keep the free updates coming!',
    rate_now: 'Rate Now',
    not_now: 'Not now',
    notifications_dialog: '"IELTS" Would Like to Send You Notifications',
    allow: 'Allow',
    dont_allow: "Don't Allow",
    personal_title: 'Make it personal',
    personal_desc: 'Allow tracking to unlock a smarter, more personal IELTS experience.',
    personal_opt1: 'Personalized for you',
    personal_opt1_desc: 'Study recommendations tuned to your goals and level',
    personal_opt2: 'Smarter over time',
    personal_opt2_desc: 'The more you practice, the better it adapts',
    personal_opt3: 'Help us grow',
    personal_opt3_desc: 'Lets us measure our ads so we can keep improving',
    paywall_title: 'Unlock your target IELTS Band Score',
    paywall_sub1: '12 Months (71% Off)',
    paywall_sub2: '1 Month',
    included_title: "WHAT'S INCLUDED",
    inc_speaking: 'AI Speaking Practice',
    inc_speaking_desc: 'Unlimited sessions with an AI examiner anytime. Get instant band scores on fluency, vocabulary, grammar, and pronunciation.',
    inc_mock: '300+ Full Mock Tests',
    inc_mock_desc: 'Practice with real IELTS-style tests for all four skills — Reading, Listening, Writing, and Speaking.',
    inc_writing: 'AI Writing Correction',
    inc_writing_desc: 'Submit Task 1 or Task 2 essays and receive detailed band score feedback with grammar and coherence tips.',
    inc_plan: 'Personalized Study Plan',
    inc_plan_desc: 'Your daily plan adapts to your current band score, weak skills, and exam date to keep you on track.',
    inc_track: 'Band Score Progress Tracker',
    inc_track_desc: 'Visualize your improvement over time with detailed stats.',
    dashboard_greeting_morning: 'Good Morning ☀️',
    dashboard_greeting_night: 'Good Night 🌙',
    level_pre_int: 'Pre-Intermediate',
    level_sub: 'Start practicing to track your level!',
    practice_area: 'Practice Area',
    continue_learning: 'Continue Learning',
    menu_home: 'Home',
    menu_plan: 'Plan',
    menu_tools: 'Tools',
    menu_history: 'History',
    menu_settings: 'Settings',
    essay_checker: 'Essay Checker',
    essay_checker_desc: 'Get AI band score & feedback',
    grammar_check: 'Grammar Check',
    grammar_check_desc: 'Find & fix grammar errors',
    paraphrase: 'Paraphrase',
    paraphrase_desc: 'Rewrite sentences 3 ways',
    vocabulary: 'Vocabulary',
    vocabulary_desc: 'Build IELTS vocabulary',
    speaking_samples: 'Speaking Samples',
    speaking_samples_desc: 'Band 9 answers for Part 1-3',
    writing_samples: 'Writing Samples',
    writing_samples_desc: 'Band 9 essays & reports',
    band_calculator: 'Overall Band Calculator',
    band_calculator_desc: 'Calculate your overall IELTS band from 4 skill scores',
    schedule_title: 'Your Schedule',
    ai_tools_title: 'AI Tools',
    ai_tools_desc: 'Powerful tools to boost your IELTS preparation',
    free_plan: 'Free Plan',
    upgrade_plan: 'Upgrade for full access',
    upgrade: 'Upgrade',
    exam_type: 'Exam Type',
    target_band: 'Target Band',
    reset_plan: 'Reset Study Plan',
    send_feedback: 'Send Feedback',
    rate_app: 'Rate App',
    privacy_policy: 'Privacy Policy',
    terms_of_use: 'Terms of Use',
    daily_reminders: 'Daily reminders & updates',
  },
  AR: {
    welcome_title: 'حقق درجتك التي تحلم بها في الآيلتس',
    welcome_desc: 'انضم إلى آلاف الطلاب الذين حسنوا درجاتهم من خلال الممارسة المخصصة',
    get_started: 'ابدأ الآن',
    target_score_title: 'ما هي الدرجة المستهدفة؟',
    target_score_desc: 'يساعدنا هذا في إنشاء مستوى الصعوبة المناسب.',
    continue_btn: 'متابعة',
    test_type_title: 'أي اختبار آيلتس ستأخذه؟',
    test_type_desc: 'سنقوم بتفصيل مواد الممارسة حسب نوع الاختبار الخاص بك.',
    academic: 'الأكاديمي',
    academic_desc: 'للتعليم العالي أو التسجيل المهني',
    general: 'التدريب العام',
    general_desc: 'للهجرة أو العمل أو التعليم الثانوي',
    test_date_title: 'متى اختبار الآيلتس الخاص بك؟',
    test_date_desc: 'سنقوم بضبط وتيرة خطتك الدراسية بناءً على ذلك.',
    booked_switch: 'لقد قمت بحجز اختباري',
    no_worries: 'لا تقلق!',
    flexible_plan: 'سننشئ خطة دراسية مرنة يمكنك تعديلها في أي وقت.',
    level_title: 'ما هو مستواك الحالي في اللغة الإنجليزية؟',
    level_desc: 'كن صادقًا — فهذا يساعدنا في تخصيص خطتك.',
    level_beg: 'مبتدئ',
    level_beg_desc: 'جديد في الآيلتس، النطاق 4-5',
    level_int: 'متوسط',
    level_int_desc: 'لديه بعض الخبرة، النطاق 5-6.5',
    level_adv: 'متقدم',
    level_adv_desc: 'أساس قوي، يستهدف 7+',
    stoppers_title: 'ما الذي يمنعك من الوصول إلى هدفك؟',
    stoppers_desc: 'اختر كل ما ينطبق.',
    stop_speaking: 'الثقة في التحدث',
    stop_reading: 'سرعة القراءة',
    stop_writing: 'بنية الكتابة',
    stop_listening: 'فهم الاستماع',
    stop_time: 'إدارة الوقت',
    stop_vocab: 'المفردات',
    study_time_title: 'كم من الوقت يمكنك الدراسة يومياً؟',
    study_time_desc: 'حتى 15 دقيقة يومياً تصنع فارقاً.',
    time_15: '15 دقيقة',
    time_15_desc: 'جلسات يومية سريعة',
    time_30: '30 دقيقة',
    time_30_desc: 'تقدم ثابت',
    time_1h: 'ساعة واحدة',
    time_1h_desc: 'الوتيرة الموصى بها',
    time_2h: 'ساعتين أو أكثر',
    time_2h_desc: 'إعداد مكثف',
    projected_title: 'درجتك المتوقعة في الآيلتس',
    projected_desc: 'بناءً على الطلاب الذين لديهم ملف تعريف مماثل.',
    projected_by_skill: 'المتوقع حسب المهارة',
    reminders_title: 'ابقَ على المسار الصحيح مع تذكيرات يومية',
    enjoying_title: 'هل تستمتع بالتطبيق؟',
    enjoying_desc: 'تقييمك بـ 5 نجوم يساعدنا في مواصلة تقديم التحديثات المجانية!',
    rate_now: 'تقييم الآن',
    not_now: 'ليس الآن',
    notifications_dialog: 'يريد "IELTS" إرسال إشعارات إليك',
    allow: 'سماح',
    dont_allow: 'عدم السماح',
    personal_title: 'اجعله مخصصاً',
    personal_desc: 'السماح بالتتبع لفتح تجربة آيلتس أكثر ذكاءً وشخصية.',
    personal_opt1: 'مخصص لك',
    personal_opt1_desc: 'توصيات دراسية مخصصة لأهدافك ومستواك',
    personal_opt2: 'أكثر ذكاءً بمرور الوقت',
    personal_opt2_desc: 'كلما مارست أكثر، كلما تكيف التطبيق بشكل أفضل',
    personal_opt3: 'ساعدنا على النمو',
    personal_opt3_desc: 'يتيح لنا قياس إعلاناتنا لنستمر في التحسن',
    paywall_title: 'افتح درجتك المستهدفة في الآيلتس',
    paywall_sub1: '12 شهراً (خصم 71%)',
    paywall_sub2: 'شهر واحد',
    included_title: 'ما تشمله الباقة',
    inc_speaking: 'ممارسة التحدث بالذكاء الاصطناعي',
    inc_speaking_desc: 'جلسات غير محدودة مع مصحح ذكاء اصطناعي في أي وقت. احصل على درجات فورية.',
    inc_mock: '300+ اختبار تجريبي كامل',
    inc_mock_desc: 'تدرب على اختبارات حقيقية تشمل المهارات الأربع.',
    inc_writing: 'تصحيح الكتابة بالذكاء الاصطناعي',
    inc_writing_desc: 'أرسل المقالات واحصل على تقييم تفصيلي.',
    inc_plan: 'خطة دراسية مخصصة',
    inc_plan_desc: 'تتكيف خطتك اليومية مع درجاتك ونقاط ضعفك.',
    inc_track: 'متابع تقدم الدرجات',
    inc_track_desc: 'اعرض تقدمك بمرور الوقت بإحصاءات مفصلة.',
    dashboard_greeting_morning: 'صباح الخير ☀️',
    dashboard_greeting_night: 'مساء الخير 🌙',
    level_pre_int: 'دون المتوسط',
    level_sub: 'ابدأ التدريب لتتبع مستواك!',
    practice_area: 'منطقة التدريب',
    continue_learning: 'واصل التعلم',
    menu_home: 'الرئيسية',
    menu_plan: 'الخطة',
    menu_tools: 'الأدوات',
    menu_history: 'السجل',
    menu_settings: 'الإعدادات',
    essay_checker: 'مصحح المقالات',
    essay_checker_desc: 'احصل على درجات وملاحظات بالذكاء الاصطناعي',
    grammar_check: 'فحص القواعد',
    grammar_check_desc: 'ابحث عن الأخطاء النحوية وصححها',
    paraphrase: 'إعادة الصياغة',
    paraphrase_desc: 'أعد صياغة الجمل بثلاث طرق',
    vocabulary: 'المفردات',
    vocabulary_desc: 'ابنِ مفرداتك للآيلتس',
    speaking_samples: 'عينات التحدث',
    speaking_samples_desc: 'إجابات نموذجية للنطاق 9 للآجزاء 1-3',
    writing_samples: 'عينات الكتابة',
    writing_samples_desc: 'مقالات وتقارير نموذجية للنطاق 9',
    band_calculator: 'حاسبة النطاق الإجمالي',
    band_calculator_desc: 'احسب درجتك الإجمالية من درجات المهارات الأربع',
    schedule_title: 'جدولك الدراسي',
    ai_tools_title: 'أدوات الذكاء الاصطناعي',
    ai_tools_desc: 'أدوات قوية لتعزيز استعدادك للآيلتس',
    free_plan: 'الخطة المجانية',
    upgrade_plan: 'ترقية للوصول الكامل',
    upgrade: 'ترقية',
    exam_type: 'نوع الاختبار',
    target_band: 'الدرجة المستهدفة',
    reset_plan: 'إعادة تعيين خطة الدراسة',
    send_feedback: 'أرسل ملاحظاتك',
    rate_app: 'تقييم التطبيق',
    privacy_policy: 'سياسة الخصوصية',
    terms_of_use: 'شروط الاستخدام',
    daily_reminders: 'التذكيرات والتحديثات اليومية',
  },
};

export const languagesList = [
  { code: 'EN', name: 'English' },
  { code: 'AR', name: 'العربية (Arabic)' },
  { code: 'FR', name: 'Français (French)' },
  { code: 'DE', name: 'Deutsch (German)' },
  { code: 'IT', name: 'Italiano (Italian)' },
  { code: 'JA', name: '日本語 (Japanese)' },
  { code: 'KO', name: '한국어 (Korean)' },
  { code: 'PT', name: 'Português (Portuguese)' },
  { code: 'RU', name: 'Русский (Russian)' },
  { code: 'ZH', name: '简体中文 (Simplified Chinese)' },
  { code: 'ES', name: 'Español (Spanish)' },
  { code: 'TH', name: 'ไทย (Thai)' },
  { code: 'ZHT', name: '繁體中文 (Traditional Chinese)' },
  { code: 'UK', name: 'Українська (Ukrainian)' },
  { code: 'VI', name: 'Tiếng Việt (Vietnamese)' },
];

export function getTranslation(key: string, locale: string = 'EN'): string {
  if (localizedValues[locale] && localizedValues[locale][key]) {
    return localizedValues[locale][key];
  }
  return localizedValues['EN'][key] || key;
}
