import { Injectable, Logger, OnApplicationBootstrap } from '@nestjs/common';
import { PrismaService } from '../prisma.service';
import { AiService } from './ai.service';
import { join } from 'path';
import * as fs from 'fs';
import axios from 'axios';

@Injectable()
export class QuestionSchedulerService implements OnApplicationBootstrap {
  private readonly logger = new Logger(QuestionSchedulerService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly aiService: AiService,
  ) {}

  onApplicationBootstrap() {
    // Run the check on application startup
    setTimeout(() => {
      this.checkAndGenerateDailyQuestions().catch((err) => {
        this.logger.error('Error in daily questions auto-generation:', err);
      });
    }, 5000); // Wait 5 seconds after boot to let initialization finish
  }

  private extractJson(text: string): string {
    const startArr = text.indexOf('[');
    const startObj = text.indexOf('{');
    
    let start = -1;
    let end = -1;
    
    if (startArr !== -1 && (startObj === -1 || startArr < startObj)) {
      start = startArr;
      end = text.lastIndexOf(']');
    } else if (startObj !== -1) {
      start = startObj;
      end = text.lastIndexOf('}');
    }
    
    if (start === -1 || end === -1 || end < start) {
      return text.replace(/^```json/, '').replace(/```$/, '').trim();
    }
    
    return text.substring(start, end + 1).trim();
  }

  private async generateFreeTts(text: string): Promise<Buffer> {
    const chunks: string[] = [];
    const words = text.split(/\s+/);
    let currentChunk = '';

    for (const word of words) {
      if ((currentChunk + ' ' + word).length > 180) {
        if (currentChunk) chunks.push(currentChunk.trim());
        currentChunk = word;
      } else {
        currentChunk = currentChunk ? currentChunk + ' ' + word : word;
      }
    }
    if (currentChunk) chunks.push(currentChunk.trim());

    const buffers: Buffer[] = [];
    for (const chunk of chunks) {
      const url = `https://translate.google.com/translate_tts?ie=UTF-8&tl=en&client=tw-ob&q=${encodeURIComponent(
        chunk
      )}`;
      
      const response = await axios.get(url, {
        responseType: 'arraybuffer',
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.0.0 Safari/537.36'
        }
      });
      
      buffers.push(Buffer.from(response.data));
    }

    return Buffer.concat(buffers);
  }

  private async generateTtsAudio(text: string, openAiKey?: string): Promise<Buffer> {
    if (openAiKey) {
      try {
        const response = await axios.post(
          'https://api.openai.com/v1/audio/speech',
          {
            model: 'tts-1',
            input: text,
            voice: 'alloy',
            response_format: 'mp3',
          },
          {
            headers: {
              Authorization: `Bearer ${openAiKey}`,
              'Content-Type': 'application/json',
            },
            responseType: 'arraybuffer',
          }
        );
        return Buffer.from(response.data);
      } catch (err: any) {
        this.logger.warn(`[OpenAI_TTS_Failed] Falling back to Free Google TTS: ${err.message}`);
      }
    }
    return this.generateFreeTts(text);
  }

  async checkAndGenerateDailyQuestions() {
    // 1. Check if AI features are enabled
    const aiEnabled = await this.prisma.appSettings.findUnique({ where: { key: 'ai_enabled' } });
    if (!aiEnabled || aiEnabled.value !== 'true') {
      this.logger.warn('AI is globally disabled. Skipping daily questions auto-generation.');
      return;
    }

    // 2. Check current total resources to respect the 1000 limit safety cap
    const [pqCount, wpCount, spCount] = await Promise.all([
      this.prisma.practiceQuestion.count(),
      this.prisma.writingPrompt.count(),
      this.prisma.speakingPrompt.count(),
    ]);
    const totalCount = pqCount + wpCount + spCount;
    this.logger.log(`Current total practice resources: ${totalCount}/1000 (Questions: ${pqCount}, Writing: ${wpCount}, Speaking: ${spCount})`);

    if (totalCount >= 1000) {
      this.logger.log('Database already has 1000+ practice questions. Auto-generation skipped.');
      return;
    }

    // 3. Check if we already generated questions today
    const todayStr = new Date().toISOString().split('T')[0];
    let lastGenDateSetting = await this.prisma.appSettings.findUnique({ where: { key: 'last_auto_generation_date' } });
    if (!lastGenDateSetting) {
      lastGenDateSetting = await this.prisma.appSettings.create({
        data: {
          key: 'last_auto_generation_date',
          value: '',
          description: 'Last date (YYYY-MM-DD) when daily practice questions were auto-generated by AI',
        },
      });
    }

    if (lastGenDateSetting.value === todayStr) {
      this.logger.log(`Daily questions for ${todayStr} have already been generated today.`);
      return;
    }

    this.logger.log(`Starting auto-generation of 20 practice questions for ${todayStr}...`);

    const themes = [
      'Climate Change and Eco-friendly Living',
      'Artificial Intelligence and Future Jobs',
      'The Impact of Fast Fashion on the Environment',
      'Healthy Diets and Government Regulations',
      'Public Transport vs Private Cars in Megacities',
      'Cultural Preservation in a Globalized World',
      'Remote Work and Family-Life Balance',
      'Space Exploration and Funding Priorities',
      'Higher Education Tuition and Social Inequality',
      'The Role of Traditional Media in the Digital Age',
    ];
    const theme = themes[Math.floor(Math.random() * themes.length)];

    let successfullyGeneratedCount = 0;

    // Fetch or create modules defensively
    let listeningMod = await this.prisma.module.findFirst({ where: { name: 'LISTENING' } });
    if (!listeningMod) {
      listeningMod = await this.prisma.module.create({ data: { name: 'LISTENING' } });
    }
    let readingMod = await this.prisma.module.findFirst({ where: { name: 'READING' } });
    if (!readingMod) {
      readingMod = await this.prisma.module.create({ data: { name: 'READING' } });
    }

    // --- GENERATE LISTENING QUESTIONS (3) ---
    if (listeningMod) {
      try {
        const prompt = `You are an expert IELTS Listening Generator. Generate an IELTS Listening practice track dialogue/lecture transcript and a set of 3 questions based on the theme "${theme}".
Difficulty: INTERMEDIATE.
Return a valid JSON object matching this schema. Do not include markdown code block syntax (like \`\`\`json). Output raw JSON.
{
  "title": "IELTS Listening Part 1: Conversation about...",
  "transcript": "Full dialogue or monologue script. Use clear turn-taking markers like Speaker A: and Speaker B:.",
  "duration": 300,
  "questions": [
    {
      "questionType": "MULTIPLE_CHOICE",
      "instruction": "Answer the question based on the listening track.",
      "questionText": "What is...",
      "explanation": "Detailed explanation of the correct answer.",
      "options": [
        { "optionText": "option label", "optionLetter": "A", "isCorrect": true },
        { "optionText": "option label", "optionLetter": "B", "isCorrect": false }
      ],
      "answers": [
        { "correctText": "the exact text answer" }
      ]
    }
  ]
}`;
        const aiResponse = await this.aiService.generateChatCompletion([{ role: 'user', content: prompt }]);
        const jsonText = this.extractJson(aiResponse.text);
        const data = JSON.parse(jsonText);

        // Try to generate TTS audio using OpenAI, fallback to free Google TTS
        let audioUrl = 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3'; // Absolute fallback
        
        const openAiKeySetting = await this.prisma.appSettings.findFirst({
          where: { key: 'ai_openai_key' }
        });
        const openAiKey = openAiKeySetting ? this.aiService.decryptKey(openAiKeySetting.value) : '';

        try {
          const audioBuffer = await this.generateTtsAudio(data.transcript, openAiKey);
          const uploadsDir = join(__dirname, '..', '..', 'uploads', 'listening');
          if (!fs.existsSync(uploadsDir)) {
            fs.mkdirSync(uploadsDir, { recursive: true });
          }
          const filename = `${Date.now()}-${Math.random().toString(36).substring(7)}.mp3`;
          const filepath = join(uploadsDir, filename);
          fs.writeFileSync(filepath, audioBuffer);
          audioUrl = `/uploads/listening/${filename}`;
        } catch (ttsErr: any) {
          this.logger.warn(`[TTS_GENERATION_FAILED] Falling back: ${ttsErr.message}`);
        }

        const audio = await this.prisma.listeningAudio.create({
          data: {
            title: data.title,
            audioUrl: audioUrl,
            transcript: data.transcript,
            duration: data.duration || 300,
            difficulty: 'INTERMEDIATE',
          }
        });

        // Create the questions
        for (const q of data.questions) {
          await this.prisma.practiceQuestion.create({
            data: {
              moduleId: listeningMod.id,
              listeningAudioId: audio.id,
              questionType: q.questionType || 'MULTIPLE_CHOICE',
              instruction: q.instruction || 'Answer the question based on the listening track.',
              questionText: q.questionText || '',
              explanation: q.explanation || '',
              difficulty: 'INTERMEDIATE',
              options: q.options ? {
                createMany: {
                  data: q.options.map((opt: any) => ({
                    optionText: opt.optionText || '',
                    optionLetter: opt.optionLetter || '',
                    isCorrect: !!opt.isCorrect,
                  })),
                }
              } : undefined,
              answers: q.answers ? {
                createMany: {
                  data: q.answers.map((ans: any) => ({
                    correctText: ans.correctText || '',
                  })),
                }
              } : undefined,
            }
          });
          successfullyGeneratedCount++;
        }
      } catch (err: any) {
        this.logger.error(`Failed to generate daily Listening questions: ${err.message}`);
      }
    }

    // --- GENERATE READING QUESTIONS (3) ---
    if (readingMod) {
      try {
        const prompt = `You are an expert IELTS Reading Generator. Generate an IELTS Reading passage (long text/article) and a set of 3 questions based on the theme "${theme}".
Difficulty: INTERMEDIATE.
Return a valid JSON object matching this schema. Do not include markdown code block syntax (like \`\`\`json). Output raw JSON.
{
  "title": "The History/Science of...",
  "text": "The full passage text (several paragraphs long) discussing the subject.",
  "questions": [
    {
      "questionType": "MULTIPLE_CHOICE",
      "instruction": "Answer the question based on the reading passage.",
      "questionText": "What does...",
      "explanation": "Detailed explanation of the correct answer.",
      "options": [
        { "optionText": "option label", "optionLetter": "A", "isCorrect": true },
        { "optionText": "option label", "optionLetter": "B", "isCorrect": false }
      ],
      "answers": [
        { "correctText": "the exact text answer" }
      ]
    }
  ]
}`;
        const aiResponse = await this.aiService.generateChatCompletion([{ role: 'user', content: prompt }]);
        const jsonText = this.extractJson(aiResponse.text);
        const data = JSON.parse(jsonText);

        const passage = await this.prisma.readingPassage.create({
          data: {
            title: data.title,
            text: data.text,
            difficulty: 'INTERMEDIATE',
          }
        });

        // Create the questions
        for (const q of data.questions) {
          await this.prisma.practiceQuestion.create({
            data: {
              moduleId: readingMod.id,
              readingPassageId: passage.id,
              questionType: q.questionType || 'MULTIPLE_CHOICE',
              instruction: q.instruction || 'Answer the question based on the reading passage.',
              questionText: q.questionText || '',
              explanation: q.explanation || '',
              difficulty: 'INTERMEDIATE',
              options: q.options ? {
                createMany: {
                  data: q.options.map((opt: any) => ({
                    optionText: opt.optionText || '',
                    optionLetter: opt.optionLetter || '',
                    isCorrect: !!opt.isCorrect,
                  })),
                }
              } : undefined,
              answers: q.answers ? {
                createMany: {
                  data: q.answers.map((ans: any) => ({
                    correctText: ans.correctText || '',
                  })),
                }
              } : undefined,
            }
          });
          successfullyGeneratedCount++;
        }
      } catch (err: any) {
        this.logger.error(`Failed to generate daily Reading questions: ${err.message}`);
      }
    }

    // --- GENERATE WRITING REPORTS (3) ---
    try {
      const prompt = `You are an expert IELTS Writing Generator. Generate exactly 3 IELTS Writing Task 1 Academic (Report description of chart/graph/map/diagram) prompts on the theme "${theme}".
Return a valid JSON array of objects. Do not include markdown code block syntax (like \`\`\`json). Output raw JSON.
Each object must match this schema:
{
  "title": "Short descriptive title of chart",
  "promptText": "Detailed instructions asking the student to summarize the key features of the visual chart"
}`;
      const aiResponse = await this.aiService.generateChatCompletion([{ role: 'user', content: prompt }]);
      const jsonText = this.extractJson(aiResponse.text);
      const prompts = JSON.parse(jsonText);
      for (const p of prompts) {
        await this.prisma.writingPrompt.create({
          data: {
            title: p.title,
            promptText: p.promptText,
            examType: 'ACADEMIC',
            taskType: 'TASK_1',
            difficulty: 'INTERMEDIATE',
          },
        });
        successfullyGeneratedCount++;
      }
    } catch (err: any) {
      this.logger.error(`Failed to generate daily Writing Reports: ${err.message}`);
    }

    // --- GENERATE WRITING LETTERS (3) ---
    try {
      const prompt = `You are an expert IELTS Writing Generator. Generate exactly 3 IELTS Writing Task 1 General (Letter description requesting details, complaining or thanking) prompts on the theme "${theme}".
Return a valid JSON array of objects. Do not include markdown code block syntax (like \`\`\`json). Output raw JSON.
Each object must match this schema:
{
  "title": "Short descriptive title of letter request",
  "promptText": "Detailed instructions outlining bullet points the student must include in their formal/informal letter response"
}`;
      const aiResponse = await this.aiService.generateChatCompletion([{ role: 'user', content: prompt }]);
      const jsonText = this.extractJson(aiResponse.text);
      const prompts = JSON.parse(jsonText);
      for (const p of prompts) {
        await this.prisma.writingPrompt.create({
          data: {
            title: p.title,
            promptText: p.promptText,
            examType: 'GENERAL',
            taskType: 'TASK_1',
            difficulty: 'INTERMEDIATE',
          },
        });
        successfullyGeneratedCount++;
      }
    } catch (err: any) {
      this.logger.error(`Failed to generate daily Writing Letters: ${err.message}`);
    }

    // --- GENERATE WRITING ESSAYS (4) ---
    try {
      const prompt = `You are an expert IELTS Writing Generator. Generate exactly 4 IELTS Writing Task 2 Essay prompts (agree/disagree, discuss both views, advantage/disadvantage) on the theme "${theme}".
Return a valid JSON array of objects. Do not include markdown code block syntax (like \`\`\`json). Output raw JSON.
Each object must match this schema:
{
  "title": "Short descriptive title of essay theme",
  "promptText": "Detailed essay topic text presenting a social opinion and asking for student arguments"
}`;
      const aiResponse = await this.aiService.generateChatCompletion([{ role: 'user', content: prompt }]);
      const jsonText = this.extractJson(aiResponse.text);
      const prompts = JSON.parse(jsonText);
      for (const p of prompts) {
        await this.prisma.writingPrompt.create({
          data: {
            title: p.title,
            promptText: p.promptText,
            examType: 'ACADEMIC',
            taskType: 'TASK_2',
            difficulty: 'INTERMEDIATE',
          },
        });
        successfullyGeneratedCount++;
      }
    } catch (err: any) {
      this.logger.error(`Failed to generate daily Writing Essays: ${err.message}`);
    }

    // --- GENERATE SPEAKING CUE CARDS (4) ---
    try {
      const prompt = `You are an expert IELTS Speaking Generator. Generate exactly 4 IELTS Speaking Part 2 Cue Cards prompts on the theme "${theme}".
Return a valid JSON array of objects. Do not include markdown code block syntax (like \`\`\`json). Output raw JSON.
Each object must match this schema:
{
  "topic": "Descriptive short title of cue card",
  "cueCardText": "Describe a place, object or person context outline",
  "followUpQuestions": ["List of 3 follow up questions for Part 3 based on this cue card"]
}`;
      const aiResponse = await this.aiService.generateChatCompletion([{ role: 'user', content: prompt }]);
      const jsonText = this.extractJson(aiResponse.text);
      const prompts = JSON.parse(jsonText);
      for (const p of prompts) {
        await this.prisma.speakingPrompt.create({
          data: {
            part: 2,
            topic: p.topic,
            cueCardText: p.cueCardText,
            followUpQuestions: p.followUpQuestions || [],
            difficulty: 'INTERMEDIATE',
          },
        });
        successfullyGeneratedCount++;
      }
    } catch (err: any) {
      this.logger.error(`Failed to generate daily Speaking prompts: ${err.message}`);
    }

    this.logger.log(`Completed daily questions auto-generation. Successfully created ${successfullyGeneratedCount} items.`);
    
    // Update the last generation date
    await this.prisma.appSettings.update({
      where: { key: 'last_auto_generation_date' },
      data: { value: todayStr },
    });
  }
}
