import { Injectable, Logger, OnApplicationBootstrap } from '@nestjs/common';
import { PrismaService } from '../prisma.service';
import { AiService } from './ai.service';

@Injectable()
export class QuestionSchedulerService implements OnApplicationBootstrap {
  private readonly logger = new Logger(QuestionSchedulerService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly aiService: AiService,
  ) {}

  onApplicationBootstrap() {
    // Run the check on application startup
    setTimeout(() => {
      this.checkAndGenerateDailyQuestions().catch((err) => {
        this.logger.error('Error in daily questions auto-generation:', err);
      });
    }, 5000); // Wait 5 seconds after boot to let initialization finish
  }

  private extractJson(text: string): string {
    const startArr = text.indexOf('[');
    const startObj = text.indexOf('{');
    
    let start = -1;
    let end = -1;
    
    if (startArr !== -1 && (startObj === -1 || startArr < startObj)) {
      start = startArr;
      end = text.lastIndexOf(']');
    } else if (startObj !== -1) {
      start = startObj;
      end = text.lastIndexOf('}');
    }
    
    if (start === -1 || end === -1 || end < start) {
      return text.replace(/^```json/, '').replace(/```$/, '').trim();
    }
    
    return text.substring(start, end + 1).trim();
  }

  async checkAndGenerateDailyQuestions() {
    // 1. Check if AI features are enabled
    const aiEnabled = await this.prisma.appSettings.findUnique({ where: { key: 'ai_enabled' } });
    if (!aiEnabled || aiEnabled.value !== 'true') {
      this.logger.warn('AI is globally disabled. Skipping daily questions auto-generation.');
      return;
    }

    // 2. Check current total resources to respect the 1000 limit safety cap
    const [pqCount, wpCount, spCount] = await Promise.all([
      this.prisma.practiceQuestion.count(),
      this.prisma.writingPrompt.count(),
      this.prisma.speakingPrompt.count(),
    ]);
    const totalCount = pqCount + wpCount + spCount;
    this.logger.log(`Current total practice resources: ${totalCount}/1000 (Questions: ${pqCount}, Writing: ${wpCount}, Speaking: ${spCount})`);

    if (totalCount >= 1000) {
      this.logger.log('Database already has 1000+ practice questions. Auto-generation skipped.');
      return;
    }

    // 3. Check if we already generated questions today
    const todayStr = new Date().toISOString().split('T')[0];
    let lastGenDateSetting = await this.prisma.appSettings.findUnique({ where: { key: 'last_auto_generation_date' } });
    if (!lastGenDateSetting) {
      lastGenDateSetting = await this.prisma.appSettings.create({
        data: {
          key: 'last_auto_generation_date',
          value: '',
          description: 'Last date (YYYY-MM-DD) when daily practice questions were auto-generated by AI',
        },
      });
    }

    if (lastGenDateSetting.value === todayStr) {
      this.logger.log(`Daily questions for ${todayStr} have already been generated today.`);
      return;
    }

    this.logger.log(`Starting auto-generation of 20 practice questions for ${todayStr}...`);

    const themes = [
      'Climate Change and Eco-friendly Living',
      'Artificial Intelligence and Future Jobs',
      'The Impact of Fast Fashion on the Environment',
      'Healthy Diets and Government Regulations',
      'Public Transport vs Private Cars in Megacities',
      'Cultural Preservation in a Globalized World',
      'Remote Work and Family-Life Balance',
      'Space Exploration and Funding Priorities',
      'Higher Education Tuition and Social Inequality',
      'The Role of Traditional Media in the Digital Age',
    ];
    const theme = themes[Math.floor(Math.random() * themes.length)];

    let successfullyGeneratedCount = 0;

    // Fetch or create modules defensively
    let listeningMod = await this.prisma.module.findFirst({ where: { name: 'LISTENING' } });
    if (!listeningMod) {
      listeningMod = await this.prisma.module.create({ data: { name: 'LISTENING' } });
    }
    let readingMod = await this.prisma.module.findFirst({ where: { name: 'READING' } });
    if (!readingMod) {
      readingMod = await this.prisma.module.create({ data: { name: 'READING' } });
    }

    // --- GENERATE LISTENING QUESTIONS (3) ---
    if (listeningMod) {
      try {
        const prompt = `You are an expert IELTS Question Generator. Generate exactly 3 IELTS practice questions for the module "Listening" on the theme "${theme}".
Difficulty: INTERMEDIATE. Return a valid JSON array of objects. Do not include markdown code block syntax (like \`\`\`json). Output raw JSON.
Each object must match this schema:
{
  "questionType": "MULTIPLE_CHOICE", // or "FILL_IN_THE_BLANK"
  "instruction": "string describing the test instruction",
  "questionText": "the actual question text with blanks if applicable",
  "explanation": "detailed explanation of the correct answer",
  "options": [
    { "optionText": "option label", "optionLetter": "A", "isCorrect": true },
    { "optionText": "option label", "optionLetter": "B", "isCorrect": false }
  ],
  "answers": [
    { "correctText": "the exact string matches" }
  ]
}`;
        const aiResponse = await this.aiService.generateChatCompletion([{ role: 'user', content: prompt }]);
        const jsonText = this.extractJson(aiResponse.text);
        const questions = JSON.parse(jsonText);
        for (const q of questions) {
          await this.prisma.practiceQuestion.create({
            data: {
              moduleId: listeningMod.id,
              questionType: q.questionType,
              instruction: q.instruction,
              questionText: q.questionText,
              explanation: q.explanation,
              options: q.options ? {
                createMany: {
                  data: q.options.map((opt: any) => ({
                    optionText: opt.optionText,
                    optionLetter: opt.optionLetter || '',
                    isCorrect: !!opt.isCorrect,
                  })),
                }
              } : undefined,
              answers: q.answers ? {
                createMany: {
                  data: q.answers.map((ans: any) => ({
                    correctText: ans.correctText,
                    acceptableTexts: ans.acceptableTexts || [],
                  })),
                }
              } : undefined,
            },
          });
          successfullyGeneratedCount++;
        }
      } catch (err: any) {
        this.logger.error(`Failed to generate daily Listening questions: ${err.message}`);
      }
    }

    // --- GENERATE READING QUESTIONS (3) ---
    if (readingMod) {
      try {
        const prompt = `You are an expert IELTS Question Generator. Generate exactly 3 IELTS practice questions for the module "Reading" on the theme "${theme}".
Difficulty: INTERMEDIATE. Return a valid JSON array of objects. Do not include markdown code block syntax (like \`\`\`json). Output raw JSON.
Each object must match this schema:
{
  "questionType": "MULTIPLE_CHOICE", // or "FILL_IN_THE_BLANK"
  "instruction": "string describing the test instruction",
  "questionText": "the actual question text with blanks if applicable",
  "explanation": "detailed explanation of the correct answer",
  "options": [
    { "optionText": "option label", "optionLetter": "A", "isCorrect": true },
    { "optionText": "option label", "optionLetter": "B", "isCorrect": false }
  ],
  "answers": [
    { "correctText": "the exact string matches" }
  ]
}`;
        const aiResponse = await this.aiService.generateChatCompletion([{ role: 'user', content: prompt }]);
        const jsonText = this.extractJson(aiResponse.text);
        const questions = JSON.parse(jsonText);
        for (const q of questions) {
          await this.prisma.practiceQuestion.create({
            data: {
              moduleId: readingMod.id,
              questionType: q.questionType,
              instruction: q.instruction,
              questionText: q.questionText,
              explanation: q.explanation,
              options: q.options ? {
                createMany: {
                  data: q.options.map((opt: any) => ({
                    optionText: opt.optionText,
                    optionLetter: opt.optionLetter || '',
                    isCorrect: !!opt.isCorrect,
                  })),
                }
              } : undefined,
              answers: q.answers ? {
                createMany: {
                  data: q.answers.map((ans: any) => ({
                    correctText: ans.correctText,
                    acceptableTexts: ans.acceptableTexts || [],
                  })),
                }
              } : undefined,
            },
          });
          successfullyGeneratedCount++;
        }
      } catch (err: any) {
        this.logger.error(`Failed to generate daily Reading questions: ${err.message}`);
      }
    }

    // --- GENERATE WRITING REPORTS (3) ---
    try {
      const prompt = `You are an expert IELTS Writing Generator. Generate exactly 3 IELTS Writing Task 1 Academic (Report description of chart/graph/map/diagram) prompts on the theme "${theme}".
Return a valid JSON array of objects. Do not include markdown code block syntax (like \`\`\`json). Output raw JSON.
Each object must match this schema:
{
  "title": "Short descriptive title of chart",
  "promptText": "Detailed instructions asking the student to summarize the key features of the visual chart"
}`;
      const aiResponse = await this.aiService.generateChatCompletion([{ role: 'user', content: prompt }]);
      const jsonText = this.extractJson(aiResponse.text);
      const prompts = JSON.parse(jsonText);
      for (const p of prompts) {
        await this.prisma.writingPrompt.create({
          data: {
            title: p.title,
            promptText: p.promptText,
            examType: 'ACADEMIC',
            taskType: 'TASK_1',
            difficulty: 'INTERMEDIATE',
          },
        });
        successfullyGeneratedCount++;
      }
    } catch (err: any) {
      this.logger.error(`Failed to generate daily Writing Reports: ${err.message}`);
    }

    // --- GENERATE WRITING LETTERS (3) ---
    try {
      const prompt = `You are an expert IELTS Writing Generator. Generate exactly 3 IELTS Writing Task 1 General (Letter description requesting details, complaining or thanking) prompts on the theme "${theme}".
Return a valid JSON array of objects. Do not include markdown code block syntax (like \`\`\`json). Output raw JSON.
Each object must match this schema:
{
  "title": "Short descriptive title of letter request",
  "promptText": "Detailed instructions outlining bullet points the student must include in their formal/informal letter response"
}`;
      const aiResponse = await this.aiService.generateChatCompletion([{ role: 'user', content: prompt }]);
      const jsonText = this.extractJson(aiResponse.text);
      const prompts = JSON.parse(jsonText);
      for (const p of prompts) {
        await this.prisma.writingPrompt.create({
          data: {
            title: p.title,
            promptText: p.promptText,
            examType: 'GENERAL',
            taskType: 'TASK_1',
            difficulty: 'INTERMEDIATE',
          },
        });
        successfullyGeneratedCount++;
      }
    } catch (err: any) {
      this.logger.error(`Failed to generate daily Writing Letters: ${err.message}`);
    }

    // --- GENERATE WRITING ESSAYS (4) ---
    try {
      const prompt = `You are an expert IELTS Writing Generator. Generate exactly 4 IELTS Writing Task 2 Essay prompts (agree/disagree, discuss both views, advantage/disadvantage) on the theme "${theme}".
Return a valid JSON array of objects. Do not include markdown code block syntax (like \`\`\`json). Output raw JSON.
Each object must match this schema:
{
  "title": "Short descriptive title of essay theme",
  "promptText": "Detailed essay topic text presenting a social opinion and asking for student arguments"
}`;
      const aiResponse = await this.aiService.generateChatCompletion([{ role: 'user', content: prompt }]);
      const jsonText = this.extractJson(aiResponse.text);
      const prompts = JSON.parse(jsonText);
      for (const p of prompts) {
        await this.prisma.writingPrompt.create({
          data: {
            title: p.title,
            promptText: p.promptText,
            examType: 'ACADEMIC',
            taskType: 'TASK_2',
            difficulty: 'INTERMEDIATE',
          },
        });
        successfullyGeneratedCount++;
      }
    } catch (err: any) {
      this.logger.error(`Failed to generate daily Writing Essays: ${err.message}`);
    }

    // --- GENERATE SPEAKING CUE CARDS (4) ---
    try {
      const prompt = `You are an expert IELTS Speaking Generator. Generate exactly 4 IELTS Speaking Part 2 Cue Cards prompts on the theme "${theme}".
Return a valid JSON array of objects. Do not include markdown code block syntax (like \`\`\`json). Output raw JSON.
Each object must match this schema:
{
  "topic": "Descriptive short title of cue card",
  "cueCardText": "Describe a place, object or person context outline",
  "followUpQuestions": ["List of 3 follow up questions for Part 3 based on this cue card"]
}`;
      const aiResponse = await this.aiService.generateChatCompletion([{ role: 'user', content: prompt }]);
      const jsonText = this.extractJson(aiResponse.text);
      const prompts = JSON.parse(jsonText);
      for (const p of prompts) {
        await this.prisma.speakingPrompt.create({
          data: {
            part: 2,
            topic: p.topic,
            cueCardText: p.cueCardText,
            followUpQuestions: p.followUpQuestions || [],
            difficulty: 'INTERMEDIATE',
          },
        });
        successfullyGeneratedCount++;
      }
    } catch (err: any) {
      this.logger.error(`Failed to generate daily Speaking prompts: ${err.message}`);
    }

    this.logger.log(`Completed daily questions auto-generation. Successfully created ${successfullyGeneratedCount} items.`);
    
    // Update the last generation date
    await this.prisma.appSettings.update({
      where: { key: 'last_auto_generation_date' },
      data: { value: todayStr },
    });
  }
}
