import { Injectable, OnApplicationBootstrap, Logger } from '@nestjs/common';
import { PrismaService } from '../prisma.service';
import { AiService } from './ai.service';

@Injectable()
export class QuestionSchedulerService implements OnApplicationBootstrap {
  private readonly logger = new Logger(QuestionSchedulerService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly aiService: AiService,
  ) {}

  onApplicationBootstrap() {
    // Run the check asynchronously so it doesn't block server startup
    setTimeout(() => {
      this.checkAndGenerateDailyQuestions().catch((err) => {
        this.logger.error('Error in daily questions auto-generation:', err);
      });
    }, 5000);
  }

  async checkAndGenerateDailyQuestions() {
    this.logger.log('Checking database question count for auto-generation...');
    
    // 1. Check if AI features are enabled
    const aiEnabledSetting = await this.prisma.appSettings.findUnique({
      where: { key: 'ai_enabled' },
    });
    if (!aiEnabledSetting || aiEnabledSetting.value !== 'true') {
      this.logger.warn('AI is globally disabled. Skipping daily questions auto-generation.');
      return;
    }

    // 2. Check total question count limit
    const totalQuestions = await this.prisma.practiceQuestion.count();
    this.logger.log(`Current total practice questions: ${totalQuestions}/1000`);
    
    if (totalQuestions >= 1000) {
      this.logger.log('Database already has 1000+ practice questions. Auto-generation skipped.');
      return;
    }

    // 3. Check if we already ran auto-generation today
    const todayStr = new Date().toISOString().split('T')[0];
    let lastGenSetting = await this.prisma.appSettings.findUnique({
      where: { key: 'last_auto_generation_date' },
    });

    if (!lastGenSetting) {
      lastGenSetting = await this.prisma.appSettings.create({
        data: {
          key: 'last_auto_generation_date',
          value: '',
          description: 'Last date (YYYY-MM-DD) when daily practice questions were auto-generated by AI',
        },
      });
    }

    if (lastGenSetting.value === todayStr) {
      this.logger.log(`Daily questions for ${todayStr} have already been generated today.`);
      return;
    }

    this.logger.log(`Starting auto-generation of 20 practice questions for ${todayStr}...`);
    
    // 4. Fetch modules
    const modules = await this.prisma.module.findMany();
    if (modules.length === 0) {
      this.logger.error('No modules found in database to associate questions with.');
      return;
    }

    // Common IELTS themes
    const themes = [
      'Education and Learning',
      'Technology and Digitalization',
      'Environmental Conservation and Climate Change',
      'Travel and Tourism',
      'Health, Fitness and Medicine',
      'Work, Employment and Business',
      'Family relationships and Social Structures',
      'Arts, Culture and Literature',
      'Science, Innovation and Discovery',
      'Urbanization and Modern Cities',
    ];

    let successfullyGeneratedCount = 0;

    // We distribute 20 questions across the modules (5 questions per module)
    for (const mod of modules) {
      const theme = themes[Math.floor(Math.random() * themes.length)];
      const countPerModule = 5;
      
      this.logger.log(`Generating ${countPerModule} questions for module: ${mod.name} with theme: "${theme}"`);

      const prompt = `You are an expert IELTS Question Generator. Generate exactly ${countPerModule} IELTS practice questions for the module "${mod.name}" on the theme "${theme}".
The questions must be of difficulty level "INTERMEDIATE".
Output a valid JSON array of objects. Do not include markdown code block syntax (like \`\`\`json). Output raw JSON.
Each object in the array must match this schema:
{
  "questionType": "MULTIPLE_CHOICE", // or "FILL_IN_THE_BLANK"
  "instruction": "string describing the test instruction",
  "questionText": "the actual question text with blanks if applicable",
  "explanation": "detailed grammatical/lexical explanation of the correct answer",
  "options": [
    { "optionText": "option label", "optionLetter": "A", "isCorrect": true },
    { "optionText": "option label", "optionLetter": "B", "isCorrect": false }
  ],
  "answers": [
    { "correctText": "the exact string matches" }
  ]
}`;

      try {
        const aiResponse = await this.aiService.generateChatCompletion([
          { role: 'user', content: prompt }
        ]);

        const responseText = aiResponse.text.trim();
        const jsonText = responseText.replace(/^```json/, '').replace(/```$/, '').trim();
        const questions = JSON.parse(jsonText);

        for (const q of questions) {
          await this.prisma.practiceQuestion.create({
            data: {
              moduleId: mod.id,
              questionType: q.questionType,
              difficulty: 'INTERMEDIATE',
              instruction: q.instruction,
              questionText: q.questionText,
              explanation: q.explanation,
              options: q.options ? {
                createMany: {
                  data: q.options.map((opt: any) => ({
                    optionText: opt.optionText,
                    optionLetter: opt.optionLetter || '',
                    isCorrect: !!opt.isCorrect,
                  })),
                }
              } : undefined,
              answers: q.answers ? {
                createMany: {
                  data: q.answers.map((ans: any) => ({
                    correctText: ans.correctText,
                    acceptableTexts: ans.acceptableTexts || [],
                  })),
                }
              } : undefined,
            },
          });
          successfullyGeneratedCount++;
        }
      } catch (err: any) {
        this.logger.error(`Failed to generate questions for module ${mod.name}: ${err.message}`);
      }
    }

    this.logger.log(`Completed daily questions auto-generation. Successfully created ${successfullyGeneratedCount} questions.`);
    
    // Update the last generation date
    await this.prisma.appSettings.update({
      where: { key: 'last_auto_generation_date' },
      data: { value: todayStr },
    });
  }
}
